version: "3"
services:
  postgres:
    container_name: pqsql
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    env_file:
      - .env
    networks:
      - postgres
 
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - pgadmin:/root/.pgadmin
    env_file:
      - .env
    networks:
      - postgres
 
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: